@JobTrackerClient_HostAddress = http://localhost:5104
@Swagger = http://localhost:5104/swagger/index.html
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZmEzZGI1ZC1hZjM0LTRhYjUtYmY4MS04MWNkM2I4MGRlNjAiLCJlbWFpbCI6Im1hcnVmc2Fya2VyLndvcmtAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ik1kLiBNYXJ1ZiBTYXJrZXIiLCJleHAiOjE3Nzg3Njk1MTMsImlzcyI6IkpvYlRyYWNrZXJBUEkiLCJhdWQiOiJKb2JUcmFja2VyQ2xpZW50In0.YIRSXLO1V4fDq_A-ijB9JF3YINyEJt9u0MDEIlJrBuo

###
POST {{JobTrackerClient_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "Name": "Md. Maruf Sarker",
  "email": "marufsarker.work@gmail.com",
  "password": "Mmsmaruf123!",
  "confirmPassword": "Mmsmaruf123!"
}

###
POST {{JobTrackerClient_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "marufsarker.work@gmail.com",
  "password": "Mmsmaruf123!"
}

###
POST {{JobTrackerClient_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "demo@jobtracker.dev",
  "password": "Demo@123"
}

###
GET {{JobTrackerClient_HostAddress}}/api/dashboard/summary
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{JobTrackerClient_HostAddress}}/api/dashboard/status-chart
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{JobTrackerClient_HostAddress}}/api/dashboard/platform-chart
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{JobTrackerClient_HostAddress}}/api/companies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{JobTrackerClient_HostAddress}}/api/jobapplications
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}