@JobTrackerClient_HostAddress = http://localhost:5104
@Swagger = http://localhost:5104/swagger/index.html
@Token = YOUR_JWT_TOKEN_HERE

###
POST {{JobTrackerClient_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "Name": "Demo User",
  "email": "demo@jobtracker.dev",
  "password": "Password123!",
  "confirmPassword": "Password123!"
}

###
POST {{JobTrackerClient_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "demo@jobtracker.dev",
  "password": "Password123!"
}

###
GET {{JobTrackerClient_HostAddress}}/api/dashboard/summary
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{JobTrackerClient_HostAddress}}/api/companies
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}

###
GET {{JobTrackerClient_HostAddress}}/api/jobapplications
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{Token}}