name: Server CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore JobTracker.API/JobTracker.API.csproj

      - name: Build project
        run: dotnet build JobTracker.API/JobTracker.API.csproj --no-restore

      - name: Run tests
        run: dotnet test JobTracker.API.Tests/JobTracker.API.Tests.csproj