name: Docker CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./server/JobTracker.API
          file: ./server/JobTracker.API/Dockerfile
          push: false

      - name: Build Client Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          file: ./client/Dockerfile
          push: false

      - name: Test Docker Compose Build
        run: docker compose build
