using JobTracker.API.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace JobTracker.API.Configs;

public class AppDbContext : IdentityDbContext<User, IdentityRole<Guid>, Guid>
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) {}

    public DbSet<Priority> Priorities => Set<Priority>();
    public DbSet<JobType> JobTypes => Set<JobType>();
    public DbSet<SourcePlatform> SourcePlatforms => Set<SourcePlatform>();
    public DbSet<WorkType> WorkTypes => Set<WorkType>();
    public DbSet<ApplicationStatus> ApplicationStatuses => Set<ApplicationStatus>();
    public DbSet<JobApplication> JobApplications => Set<JobApplication>();
    public DbSet<Company> Companies => Set<Company>();
    public DbSet<InterviewRound> InterviewRounds => Set<InterviewRound>();
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();
    public DbSet<JobRole> JobRoles => Set<JobRole>();
    public DbSet<UserProfile> UserProfiles => Set<UserProfile>();
    public DbSet<RejectionRetrospective> RejectionRetrospectives => Set<RejectionRetrospective>();
    public DbSet<UserAiInsight> UserAiInsights => Set<UserAiInsight>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Force CreatedAt / UpdatedAt to be generated by the DB as UTC timestamps
        // This avoids DateTime Kind=Unspecified errors with Npgsql 8+/10+
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            var createdAt = entityType.FindProperty("CreatedAt");
            if (createdAt != null)
            {
                createdAt.SetColumnType("timestamp with time zone");
                createdAt.SetDefaultValueSql("now()");
            }

            var updatedAt = entityType.FindProperty("UpdatedAt");
            if (updatedAt != null)
            {
                updatedAt.SetColumnType("timestamp with time zone");
                updatedAt.SetDefaultValueSql("now()");
            }
        }

        // DateOfBirth uses 'date' type — timezone-agnostic
        modelBuilder.Entity<UserProfile>()
            .Property(p => p.DateOfBirth)
            .HasColumnType("date");

        // JobApplication Relationships
        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.User)
            .WithMany(u => u.JobApplications)
            .HasForeignKey(j => j.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.Priority)
            .WithMany(p => p.JobApplications)
            .HasForeignKey(j => j.PriorityId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.JobType)
            .WithMany(jt => jt.JobApplications)
            .HasForeignKey(j => j.JobTypeId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.SourcePlatform)
            .WithMany(sp => sp.JobApplications)
            .HasForeignKey(j => j.SourcePlatformId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.WorkType)
            .WithMany(wt => wt.JobApplications)
            .HasForeignKey(j => j.WorkTypeId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.ApplicationStatus)
            .WithMany(s => s.JobApplications)
            .HasForeignKey(j => j.ApplicationStatusId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<JobApplication>()
            .HasOne(j => j.Company)
            .WithMany(c => c.JobApplications)
            .HasForeignKey(j => j.CompanyId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<InterviewRound>()
            .HasOne(r => r.JobApplication)
            .WithMany(j => j.InterviewRounds)
            .HasForeignKey(r => r.JobApplicationId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RejectionRetrospective>()
            .HasOne(r => r.JobApplication)
            .WithMany()
            .HasForeignKey(r => r.JobApplicationId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<RejectionRetrospective>()
            .HasOne(r => r.User)
            .WithMany()
            .HasForeignKey(r => r.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<Company>()
            .HasOne(c => c.User)
            .WithMany()
            .HasForeignKey(c => c.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<JobRole>()
            .HasOne(r => r.User)
            .WithMany()
            .HasForeignKey(r => r.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // Database Indexes for Performance Optimization
        modelBuilder.Entity<JobApplication>()
            .HasIndex(j => new { j.UserId, j.CreatedAt })
            .HasDatabaseName("IX_JobApplications_UserId_CreatedAt");

        modelBuilder.Entity<JobApplication>()
            .HasIndex(j => new { j.UserId, j.ApplicationStatusId })
            .HasDatabaseName("IX_JobApplications_UserId_ApplicationStatusId");

        modelBuilder.Entity<JobApplication>()
            .HasIndex(j => j.CompanyId)
            .HasDatabaseName("IX_JobApplications_CompanyId");

        modelBuilder.Entity<Company>()
            .HasIndex(c => c.Name)
            .HasDatabaseName("IX_Companies_Name");

        modelBuilder.Entity<Company>()
            .HasIndex(c => new { c.UserId, c.Name })
            .HasDatabaseName("IX_Companies_UserId_Name");

        modelBuilder.Entity<JobRole>()
            .HasIndex(r => r.Name)
            .HasDatabaseName("IX_JobRoles_Name");

        modelBuilder.Entity<JobRole>()
            .HasIndex(r => new { r.UserId, r.Name })
            .HasDatabaseName("IX_JobRoles_UserId_Name");

        modelBuilder.Entity<UserProfile>()
            .HasIndex(p => p.UserId)
            .IsUnique()
            .HasDatabaseName("IX_UserProfiles_UserId");

        modelBuilder.Entity<RejectionRetrospective>()
            .HasIndex(r => new { r.UserId, r.CreatedAt })
            .HasDatabaseName("IX_RejectionRetrospectives_UserId_CreatedAt");

        modelBuilder.Entity<RejectionRetrospective>()
            .HasIndex(r => r.JobApplicationId)
            .IsUnique()
            .HasDatabaseName("IX_RejectionRetrospectives_JobApplicationId");

        modelBuilder.Entity<UserAiInsight>()
            .HasOne(a => a.User)
            .WithMany()
            .HasForeignKey(a => a.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserAiInsight>()
            .HasIndex(a => new { a.UserId, a.DataHash })
            .HasDatabaseName("IX_UserAiInsights_UserId_DataHash");
    }
}